### PR TITLE
Make blueprint optional again

### LINKED ISSUE #88: Requires blueprint?
I just pulled 2.0.1 and I see that `MosaicZeroState` and `MosaicWindow` now has a dependency on @blueprintjs/core and @blueprintjs/icons. After I upgrade the version I get an error during build saying that it can't resolve @blueprintjs/icons and @blueprintjs/core. Is that intended? I saw PR #10 which removes the dependency...

### Bug report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Windows, Chrome 

#### Steps to reproduce

1. I had version 1.1.1 of `react-mosaic-component` without any blueprintjs deps.
2. Changed `1.1.1` to `2.0.1` in package.json
3. `npm install`
4. `npm run build` which runs webpack

#### Actual behavior
```
ERROR in ./node_modules/react-mosaic-component/lib/MosaicWindow.js
Module not found: Error: Can't resolve '@blueprintjs/core' in '...\node_modules\react-mosaic-component\lib'
 @ ./node_modules/react-mosaic-component/lib/MosaicWindow.js 46:13-41
 @ ./node_modules/react-mosaic-component/lib/index.js

ERROR in ./node_modules/react-mosaic-component/lib/MosaicZeroState.js
Module not found: Error: Can't resolve '@blueprintjs/core' in '...\node_modules\react-mosaic-component\lib'
 @ ./node_modules/react-mosaic-component/lib/MosaicZeroState.js 35:13-41
 @ ./node_modules/react-mosaic-component/lib/index.js
```

#### Expected behavior

No build error, no need to install @blueprintjs/core and @blueprintjs/icons.

### LINKED ISSUE #90: Example code doesn't compile
- __Package version(s)__:  react: 16.6.0, react-scripts-ts: 3.1.0, react-mosaic-component: 2.0.1, @blueprintjs/core: 3.8.0,  typescript: 3.1.6
- __Browser and OS versions__: Firefox 63, Ubuntu 18.04

#### Background

I am trying to quickly setup a React app using TypeScript and react-mosaic. 

#### Steps to reproduce

1. Use react-scripts-ts to create the simple, default app
2. Install all required modules 
3. Take the code from the _Simple Tiling_ [example](https://github.com/palantir/react-mosaic#examples). Put the code in an App.tsx file and app.css as indicated.

#### Actual behavior

Fails to compile, error: 
`(14,6): Type '{ renderTile: (id: "a") => Element; initialValue: { direction: "row"; first: "a"; second: { direction: "column"; first: "b"; second: "c"; }; splitPercentage: number; }; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Mosaic<"a">> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<MosaicControlledProps<"a">>, "resize" | "children" | "value" | "renderTile"> & Partial<...> & Partial<...>) | (IntrinsicAttributes & ... 3 more ... & Partial<...>)'.
  Type '{ renderTile: (id: "a") => Element; initialValue: { direction: "row"; first: "a"; second: { direction: "column"; first: "b"; second: "c"; }; splitPercentage: number; }; }' is not assignable to type 'Pick<Readonly<{ children?: ReactNode; }> & Readonly<MosaicUncontrolledProps<"a">>, "resize" | "children" | "renderTile" | "initialValue">'.
    Types of property 'initialValue' are incompatible.
      Type '{ direction: "row"; first: "a"; second: { direction: "column"; first: "b"; second: "c"; }; splitPercentage: number; }' is not assignable to type '"a" | MosaicParent<"a"> | null'.
        Type '{ direction: "row"; first: "a"; second: { direction: "column"; first: "b"; second: "c"; }; splitPercentage: number; }' is not assignable to type 'MosaicParent<"a">'.
          Types of property 'second' are incompatible.
            Type '{ direction: "column"; first: "b"; second: "c"; }' is not assignable to type 'MosaicNode<"a">'.
              Type '{ direction: "column"; first: "b"; second: "c"; }' is not assignable to type 'MosaicParent<"a">'.
                Types of property 'first' are incompatible.
                  Type '"b"' is not assignable to type 'MosaicNode<"a">'.`

#### Expected behavior

Example code should work fine.

### PR DESCRIPTION
**Pull request by nomcopter**
Fixes #88 
Fixes #90

Replaces #89 (thanks @adiun!)

### CODE REVIEW

**Comment by bradennapier** [comment]
Still getting errors in webpack - am I missing something here?

```
Module not found: Can't resolve '@blueprintjs/core' 
Module not found: Can't resolve '@blueprintjs/icons'

```

**Comment by nomcopter** [comment]
It works for me in my test repo, can you give more context or an example repo?

**Comment by adiun** [comment]
@bradennapier are those just warnings in the console during a build? I see those too but I believe it's expected behavior.

**Comment by luisbelloch** [comment]
We've also excluded it using webpack's `IgnorePlugin`... but still that warning is a bit misleading, it made me thing for a minute there was something wrong.

Would it be possible to avoid it?

**Comment by nomcopter** [comment]
Yeah that is pretty annoying. I'll see what I can do.

**Comment by zning** [comment]
> Yeah that is pretty annoying. I'll see what I can do.

Hi nomcopter, have we fix this issue ? It seems those warning cause build failed on Netlify. Is there a way to make it pass the build process

**Comment by nomcopter** [comment]
Does just adding the dependency work?

**Comment by zning** [comment]
> Does just adding the dependency work?

I found that the reason for this is because Netlify set the "CI" ON by default. So most of warnings(or any warning for me) will lead the build to fail. When I manually turn this off and the build was a success. Although I'm not sure turning the CI off is a good solution from the long run. Thanks for your reply and if the warnings could be fixed, that will be great!

**Pull request merged**
